### ISSUE TITLE
Improvements to our RUM implimentation

### ISSUE THREAD

**Issue by Nooshu** [alphagov/static#2516]
These apply to both static and [govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components).

## Make sure LUX data is captured when a user first accepts the cookie banner

Iniitial data is currently discarded  and the beacon only fires on the 2nd page load. SpeedCurve have guidence on how to [handle with cookie banners here](https://support.speedcurve.com/en/articles/4468508-using-lux-with-cookie-consent-banners).

## Remove the CSP workarounds `connect-src` etc

SC support have stated that they will change the content type of the image early next week so they match, this workaround will then no longer be required.

## Double check hard-coded sample rate is set to 1%

I believe we may have a 100% sample rate hard-coded somewhere. e.g. `LUX.sampleRate(100)`. What is currently happening is the JS is sending 100% traffic to SC, the UI is set to 1% so 99% of the beacons are being rejected by the server.

**Note on sample rates:** 

if we want 1% across all pages then it’s best to remove `sampleRate()` from the JS in our pages and set 1% in the UI settings. Or if we want different sample rates on different pages set targeted sample rates per page using `sampleRate()` and then use 100% in the settings.

For the moment we should remove the hard-coded `sampleRate()` and rely on the SC UI to set to 1%. 

**Todo List**:

* [x] Make sure LUX data is captured when a user first accepts the cookie banner
* [x] Remove the CSP workarounds connect-src etc
* [x] Double check hard-coded sample rate is set to 1%

**Comment by injms** [comment]
It looks as if LUX defaults to 100% if `samplerate` isn't set:
https://github.com/alphagov/static/blob/28b60eefae33341866a8e95c4c9425828b4eae75/app/assets/javascripts/libs/lux/lux.js#L75

This can be fixed by setting the `samplerate` variable inside the main `LUX` function - I'll raise a pull request to do that.

**Comment by injms** [comment]
With the release of v24.15.0 of the components gem, the sampling rate for LUX has been now set to 1% instead of the default 100%. 

As the [gem verison of LUX is now being used by Static][1], the [bump to v24.15.0 of the gem][2] should fix the sampling rate issue across all of the frontend apps regardless of the template that is being used.


[1]: https://github.com/alphagov/static/pull/2518
[2]: https://github.com/alphagov/static/pull/2519

**Comment by injms** [comment]
When running `LUX.forceSample()` locally the response has a content type of `image/webp` - I haven't been able to verify this on production as I'm not being sampled, but I think it'd be the same as the change is on SpeedCurve's server.

**Comment by injms** [comment]
A user's first page visit is now measured after (and only after) they've consented to the appropriate cookies.

This was released in [v24.18.1 of the components gem](https://github.com/alphagov/govuk_publishing_components/pull/2185), which was then bumped in Static in #2539.

**Comment by injms** [comment]
I've raised a pull request to remove the `lux.speedcurve.com` domain from the `connect-src` content security policy: https://github.com/alphagov/govuk_app_config/pull/216

**Comment by injms** [comment]
> I've raised a pull request to remove the `lux.speedcurve.com` domain from the `connect-src` content security policy: [alphagov/govuk_app_config#216](https://github.com/alphagov/govuk_app_config/pull/216)

This pull request to sort out `govuk_app_config` has been merged in and released (https://github.com/alphagov/govuk_app_config/pull/220) - this will be winging its way to all of the frontend applications over the next day or so thanks to dependabot.

**Comment by Nooshu** [comment]
Awesome work as always @injms! Closing issue as all fixed!
